version: '2'

services:
  app:
    image: aastashov/webchat:latest
    container_name: webchat-app
    build: .
    env_file:
      - .env
    volumes:
      - /opt/webchat/:/opt/webchat/
      - /opt/webchat/static/:/srv/webchat/static/
    restart: always
    depends_on:
      - srv
      - db
    networks:
      - webchat

  srv:
    image: nginx:latest
    container_name: webchat-srv
    volumes:
      - ./volumes/nginx.conf:/etc/nginx/conf.d/default.conf
      - /opt/webchat/:/opt/webchat/
    ports:
      - "81:80"
    restart: always

  db:
    image: postgres:9.6.6
    container_name: webchat-db
    env_file:
      - .env
    volumes:
      - /opt/webchat/postgresql/data:/var/lib/postgresql/data
    restart: always
    networks:
      - webchat

  cert:
    image: aastashov/certbot:latest
    build: volumes/certbot
    command: certonly -d webchat.retus.space --webroot --webroot-path /var/www/ --agree-tos --force-renewal --email alexander.astashov.vl@gmail.com
    volumes:
      - /opt/webchat/certbot-www:/var/www/
      - /opt/webchat/certbot-certs:/etc/letsencrypt

networks:
  webchat:
    external: True
