# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='message',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='dialog',
            name='created',
        ),
        migrations.RemoveField(
            model_name='dialog',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='dialog',
            name='opponent',
        ),
        migrations.RemoveField(
            model_name='dialog',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='message',
            name='modified',
        ),
        migrations.AddField(
            model_name='dialog',
            name='session_key',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='dialog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Dialog', verbose_name='Dialog'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(max_length=25, verbose_name='Author'),
        ),
    ]
