# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20171116_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dialog',
            options={'verbose_name': '\u0414\u0438\u0430\u043b\u043e\u0433', 'verbose_name_plural': '\u0414\u0438\u0430\u043b\u043e\u0433\u0438'},
        ),
        migrations.AddField(
            model_name='dialog',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
