# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20171207_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dialog',
            old_name='seen',
            new_name='unexplored',
        ),
    ]
