# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20171118_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='dialog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='chat.Dialog', verbose_name='Dialog'),
        ),
    ]
