# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 13:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0005_auto_20171118_0837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': '\u0421\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0435', 'verbose_name_plural': '\u0421\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u044f'},
        ),
        migrations.RemoveField(
            model_name='dialog',
            name='session_key',
        ),
        migrations.AddField(
            model_name='dialog',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Chief'),
        ),
        migrations.AddField(
            model_name='dialog',
            name='user',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='User session key'),
        ),
    ]
