# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20171120_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='manager',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='Chief'),
        ),
    ]
