# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20171120_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='user_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
